### ISSUE TITLE
When in Todo-tab, changing task-state first, changing rank thereafter throws exception.

### ISSUE THREAD

**Issue by rednammoc** [rockiger/akiee#4]
Setup:
*  Operating System: Elementary/Ubuntu 12.04 64 bit
*  Window-Manager: Awesome WM
*  Akiee-Version: Custom build from the current source. The old glibc was used.

How to reproduce:
1. Create two todo-tasks.
2. Go to the Todo-Tab.
3. Click the first item to change the state (Todo -> Doing).
4. Rank the first item down using the down-button.

What do you expect to see:
1. when changing state the rank-buttons should be disabled.

What do you see instead:
1. rank-buttons are enabled.
2. clicking the down-button on an item of type X within a list of type Y throws an exception.

**Comment by rockiger** [comment]
I commited a fix for the issue. My problem is, that I don't have a real solution right now. I will probably change the behavior of a row, to be removed after change of state.
